CREATE TABLE `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(250) NOT NULL UNIQUE,
  `password` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NOT NULL UNIQUE,
  `author` VARCHAR(250) NOT NULL UNIQUE,
  `external_id` VARCHAR(250) DEFAULT NULL,
  `auth_provider` VARCHAR(250) DEFAULT NULL
);